version: '3.4'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
 
  question-answer-service:
    image: question-answer-service
    build:
      context: ./PDD.NET_Api/PDD.NET.QuestionAnswer
      dockerfile: Dockerfile
    ports:
      - "5211:8080"
    depends_on:
      - mongodb
    environment:
      - ConnectionStrings__MongoDb=mongodb://mongodb:27017
  
  postgres-user-answer:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_answer_db
    ports:
      - "5433:5432" 
    volumes:
      - postgres_user_answer_data:/var/lib/postgresql/data

  user-answer-service:
    image: user-answer-service
    build:
      context: ./PDD.NET_Api/PDD.NET.UserAnswer
      dockerfile: Dockerfile
    ports:
      - "5194:8080"
    depends_on:
      - postgres-user-answer
      - rabbit
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-user-answer;Database=user_answer_db;Username=postgres;Password=postgres;
      - RABBITMQ_HOST=rabbithost
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=rabbit

      
  postgres-analytics:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analytics_db
    ports:
      - "5533:5432" 
    volumes:
      - postgres_analytics_data:/var/lib/postgresql/data
      
  analytics-service:
    image: analytics-service
    build:
      context: ./PDD.NET_Api/PDD.NET.Analytics
      dockerfile: Dockerfile
    ports:
      - "5294:8080"
    depends_on:
      - postgres-user-answer
      - rabbit
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-analytics;Database=analytics_db;Username=postgres;Password=postgres;
      - RABBITMQ_HOST=rabbithost
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=rabbit

  postgres-identity-user:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity_user_db
    ports:
      - "5434:5432" 
    volumes:
      - postgres_identity_user_data:/var/lib/postgresql/data

  postgres-identity-auth:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity_auth_db
    ports:
      - "5435:5432"  
    volumes:
      - postgres_identity_auth_data:/var/lib/postgresql/data      

  authorization:
    image: authorization
    build:
      context: ./PDD.NET_Api/PDD.NET.IdentityManager
      dockerfile: Dockerfile
    ports:
      - "5200:8080"
    depends_on:
      - postgres-identity-user
      - postgres-identity-auth 
    environment:
      - ConnectionStrings__PgUser=Host=postgres-identity-user;Database=identity_user_db;Username=postgres;Password=postgres;
      - ConnectionStrings__PgAuth=Host=postgres-identity-auth;Database=identity_auth_db;Username=postgres;Password=postgres;

 

  apigateway:
    image: apigateway
    build:
      context: ./PDD.NET_Api/PDD.NET.Gateway
      dockerfile: Dockerfile
    depends_on:
      - question-answer-service
      - user-answer-service
      - authorization
      - postgres-analytics
    ports:
      - "5288:8080"
      
  react-app:
    image: react-app
    build:
      context: ./PDD.NET.Client/pdd-net-client
      dockerfile: Dockerfile
    depends_on:
      - apigateway
    ports:
      - "9000:3000"
  
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    restart: always
    hostname: rabbithost
    environment: 
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"    

volumes:
  postgres_user_answer_data:
  postgres_identity_user_data:
  postgres_identity_auth_data:
  postgres_analytics_data:
  mongodb_data:
  rabbitmq_data:
