version: '3.4'

services:

##0 common
 # 01 React
  react-app:
    image: react-app
    container_name: 01.react-app
    build:
      context: ./PDD.NET.Client/pdd-net-client
      dockerfile: Dockerfile
    depends_on:
      - apigateway
    ports:
      - "9000:3000"
 # 02 Gateway
  apigateway:
    image: apigateway
    container_name: 02.apigateway
    build:
      context: ./PDD.NET_Api/PDD.NET.Gateway
      dockerfile: Dockerfile
    depends_on:
      - question-answer-service
      - user-answer-service
      - authorization
      - postgres-analytics
    ports:
      - "5288:8080"
 # 03 Rabbit
  rabbit:
    image: rabbitmq:3-management
    container_name: 03.rabbit
    restart: always
    hostname: rabbithost
    environment: 
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"    
##1 question-answer
 # 11 Service
  question-answer-service:
    image: question-answer-service
    container_name: 11.api.question-answer-service
    build:
      context: ./PDD.NET_Api/PDD.NET.QuestionAnswer
      dockerfile: Dockerfile
    ports:
      - "5211:8080"
    depends_on:
      - mongodb
    environment:
      - ConnectionStrings__MongoDb=mongodb://mongodb:27017
 # 12 MongoDb    
  mongodb:
    image: mongo:latest
    container_name: 12.db.mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
##2 user-answer
 # 21 Service
  user-answer-service:
    image: user-answer-service
    container_name: 21.api.user-answer-service
    build:
      context: ./PDD.NET_Api/PDD.NET.UserAnswer
      dockerfile: Dockerfile
    ports:
      - "5194:8080"
    depends_on:
      - postgres-user-answer
      - rabbit
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-user-answer;Database=user_answer_db;Username=postgres;Password=postgres;
      - RABBITMQ_HOST=rabbithost
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=rabbit
 # 22 Postgres
  postgres-user-answer:
    image: postgres:latest
    container_name: 22.db.postgres-user-answer
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_answer_db
    ports:
      - "5433:5432" 
    volumes:
      - postgres_user_answer_data:/var/lib/postgresql/data
##3 analytics
 # 31 Service  
  analytics-service:
    image: analytics-service
    container_name: 31.api.analytics-service
    build:
      context: ./PDD.NET_Api/PDD.NET.Analytics
      dockerfile: Dockerfile
    ports:
      - "5294:8080"
    depends_on:
      - postgres-analytics
      - rabbit
      - redis
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-analytics;Database=analytics_db;Username=postgres;Password=postgres;
      - RABBITMQ_HOST=rabbithost
      - RABBITMQ_USER=rabbit
      - RABBITMQ_PASS=rabbit
      - REDIS_HOST=redis
      - REDIS_PORT=6379
 # 32 Postgres
  postgres-analytics:
    image: postgres:latest
    container_name: 32.db.postgres-analytics
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analytics_db
    ports:
      - "5533:5432" 
    volumes:
      - postgres_analytics_data:/var/lib/postgresql/data      
 # 33 Redis
  redis:
    image: redis:latest
    container_name: 33.db.redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
##4 authorization
 # 41 Service
  authorization:
    image: authorization
    container_name: 41.api.authorization
    build:
      context: ./PDD.NET_Api/PDD.NET.IdentityManager
      dockerfile: Dockerfile
    ports:
      - "5200:8080"
    depends_on:
      - postgres-identity-user
      - postgres-identity-auth 
    environment:
      - ConnectionStrings__PgUser=Host=postgres-identity-user;Database=identity_user_db;Username=postgres;Password=postgres;
      - ConnectionStrings__PgAuth=Host=postgres-identity-auth;Database=identity_auth_db;Username=postgres;Password=postgres;
 # 42 Postrgess 1
  postgres-identity-auth:
    image: postgres:latest
    container_name: 42.db.postgres-identity-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity_auth_db
    ports:
      - "5435:5432"  
    volumes:
      - postgres_identity_auth_data:/var/lib/postgresql/data   
 # 43 Postrgess 2
  postgres-identity-user:
    image: postgres:latest
    container_name: 43.db.postgres-identity-user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity_user_db
    ports:
      - "5434:5432" 
    volumes:
      - postgres_identity_user_data:/var/lib/postgresql/data
               
volumes:
  postgres_user_answer_data:
  postgres_identity_user_data:
  postgres_identity_auth_data:
  postgres_analytics_data:
  mongodb_data:
  rabbitmq_data:
  redis_data:

