// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PDD.NET.Persistence;

#nullable disable

namespace PDD.NET.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240411165447_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");
#pragma warning restore 612, 618
        }
    }
}
